"""Convert the MC33 lookup table from Vega's MC33_c_library into a CUDA header.

The table comes from source/MC33_LookUpTable.h of
https://github.com/dvega68/MC33_c_library (MIT License), the reference
implementation of Vega et al., "A Fast and Memory-Saving Marching Cubes 33
Implementation with the Correct Interior Test" (JCGT 2019).

Besides extracting the array, this script re-derives every table offset the
case dispatch can produce and decodes the triangle strip at each one, so a
copy-paste or format error fails here instead of corrupting memory on the
GPU. The maximum strip length is emitted as max_triangles for buffer sizing.

Usage:

    python convert_vega_luts.py <path-to-MC33_LookUpTable.h> <output.cuh>
"""

import itertools
import re
import sys
from pathlib import Path

TABLE_SIZE = 2310


def load_table(path):
    text = Path(path).read_text()
    body = re.search(
        r"MC33_all_tables\s*\[\s*\d+\s*\]\s*=\s*\{(.*?)\};", text, re.DOTALL
    ).group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    values = [int(tok, 0) for tok in re.findall(r"0[xX][0-9a-fA-F]+|\d+", body)]
    assert len(values) == TABLE_SIZE, f"expected {TABLE_SIZE} entries, got {len(values)}"
    return values


def strip_offsets(tables):
    """Every strip offset reachable from MC33_findCase, over all cell
    configurations and all face/interior test outcomes."""
    offsets = set()
    for i in range(1, 255):
        c = tables[i ^ 0xFF] if i & 0x80 else tables[i]
        k = c & 0x7FF
        cls = c >> 12
        if cls == 0:  # cases 1, 2, 5, 8, 9, 11 and 14
            offsets.add(k)
        elif cls == 1:  # case 3
            offsets.update((159 + k, 183 + 2 * k))
        elif cls == 2:  # case 4
            offsets.update((231 + 2 * k, 239 + 6 * k))
        elif cls == 3:  # case 6
            offsets.update((335 + 3 * k, 407 + 7 * k, 575 + 5 * k))
        elif cls == 4:  # case 7
            offsets.add(695 + 3 * k)
            offsets.update(o + 5 * k for o in (719, 759, 799, 1055))
            offsets.update(o + 9 * k for o in (839, 911, 983, 1095))
        elif cls == 5:  # case 10
            offsets.update(o + 4 * k for o in (1189, 1201))
            offsets.update(o + 8 * k for o in (1213, 1237, 1261, 1285))
        elif cls == 6:  # case 12
            offsets.update(o + 4 * k for o in (1357, 1405))
            offsets.update(o + 8 * k for o in (1453, 1549, 1645, 1741))
        else:  # case 13; with ind=165 every face test returns +1 or -1
            for f in itertools.product((-1, 1), repeat=6):
                total = abs(sum(f))
                if total == 6:
                    offsets.add(1839 + 2 * f[0])  # 13.1
                elif total == 4:  # 13.2
                    kk = 21 + 11 * f[0] + 4 * f[1] + 3 * f[2] + 2 * f[3] + f[4]
                    if kk >> 4:
                        kk -= 20 if kk & 32 else 10
                    offsets.add(1845 + 3 * kk)
                elif total == 2:  # 13.3
                    a = (f[2] > 0) if f[0] < 0 else 12 + (f[2] < 0)
                    b = (f[3] < 0) if f[1] < 0 else 6 + (f[3] > 0)
                    offsets.add(1917 + 10 * (a + b) + (30 if f[4] > 0 else 0))
                else:  # 13.4 and 13.5
                    kk = ((f[1] < 0) << 1) | (f[5] < 0)
                    if f[0] * f[1] == f[5]:
                        offsets.add(2157 + 12 * kk)  # 13.4
                    else:
                        offsets.add(2285 + 6 * kk)  # 13.5.1
                        for c13 in (1, 2):  # 13.5.2
                            offsets.add(2285 + 10 * kk - 40 * c13)
    return offsets


def decode_strip(tables, offset):
    """Triangles of the strip starting after offset: one per 16-bit entry,
    three edge nibbles plus a continuation nibble."""
    triangles = []
    idx = offset
    while True:
        idx += 1
        assert idx < TABLE_SIZE, f"strip at {offset} runs past the table"
        e = tables[idx]
        tri = (e & 0xF, (e >> 4) & 0xF, (e >> 8) & 0xF)
        assert all(v <= 12 for v in tri), f"bad vertex nibble in strip at {offset}"
        triangles.append(tri)
        if e >> 12 == 0:
            return triangles


def main():
    header_path, out_path = sys.argv[1], sys.argv[2]
    tables = load_table(header_path)

    offsets = strip_offsets(tables)
    assert min(offsets) >= 127, "a strip offset points into the dispatch region"
    max_triangles = max(len(decode_strip(tables, o)) for o in offsets)

    lines = [
        "// Generated by luts/convert_vega_luts.py. Do not edit.",
        "//",
        "// MC33 lookup table from Vega et al., \"A Fast and Memory-Saving",
        "// Marching Cubes 33 Implementation with the Correct Interior Test\"",
        "// (Journal of Computer Graphics Techniques, 2019), as distributed in",
        "// https://github.com/dvega68/MC33_c_library under the MIT License:",
        "//",
        "// Copyright (c) 2019 David E. Vega M. and Javier E. Abache R.",
        "//",
        "// Permission is hereby granted, free of charge, to any person",
        "// obtaining a copy of the MC33 library code and associated",
        "// documentation files (the \"Software\"), to deal in the Software",
        "// without restriction, including without limitation the rights to",
        "// use, copy, modify, merge, publish, distribute, sublicense, and/or",
        "// sell copies of the Software, and to permit persons to whom the",
        "// Software is furnished to do so, subject to the following",
        "// conditions: The above copyright notice and this permission notice",
        "// shall be included in all copies or substantial portions of the",
        "// Software.",
        "#pragma once",
        "",
        "namespace vega {",
        "",
        f"constexpr int table_size = {TABLE_SIZE};",
        f"constexpr int max_triangles = {max_triangles};",
        "constexpr unsigned short tables[table_size] = {",
    ]
    for i in range(0, TABLE_SIZE, 12):
        row = ", ".join(f"0x{x:04X}" for x in tables[i : i + 12])
        lines.append(f"    {row},")
    lines += ["};", "", "}   // namespace vega"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(
        f"{TABLE_SIZE} entries, {len(offsets)} reachable strips, "
        f"max {max_triangles} triangles -> {out_path}"
    )


if __name__ == "__main__":
    main()
