"""Convert the MC33 lookup tables from scikit-image into a CUDA header.

The tables originate from Lewiner et al., "Efficient implementation of
Marching Cubes' cases with topological guarantees" (2003), as distributed
with scikit-image (BSD-3-Clause) in
src/_skimage2/measure/_marching_cubes_lewiner_luts.py.

Usage:

    python convert_mc33_luts.py <path-to-lewiner-luts.py> <output.cuh>
"""

import base64
import sys
from pathlib import Path

import numpy as np


def load_tables(path):
    scope = {}
    exec(Path(path).read_text(), scope)
    tables = {}
    for name, value in scope.items():
        if name.startswith("_") or not isinstance(value, tuple):
            continue
        shape, encoded = value
        data = np.frombuffer(base64.decodebytes(encoded.encode()), dtype=np.int8)
        tables[name] = data.reshape(shape)
    return tables


def main():
    luts_path, out_path = sys.argv[1], sys.argv[2]
    tables = load_tables(luts_path)

    blob = []
    lines = [
        "// Generated by luts/convert_mc33_luts.py. Do not edit.",
        "//",
        "// MC33 lookup tables from Lewiner et al., \"Efficient implementation",
        "// of Marching Cubes' cases with topological guarantees\" (2003), as",
        "// distributed with scikit-image (BSD-3-Clause).",
        "#pragma once",
        "",
        "namespace mc33 {",
        "",
    ]

    accessors = []
    for name in sorted(tables):
        array = tables[name]
        offset = len(blob)
        blob.extend(int(x) for x in array.ravel())
        dims = array.shape
        if len(dims) == 1:
            accessors.append(
                f"__host__ __device__ inline int {name}(const signed char *d, int i) "
                f"{{ return d[{offset} + i]; }}"
            )
        elif len(dims) == 2:
            accessors.append(
                f"__host__ __device__ inline int {name}(const signed char *d, int i, int j) "
                f"{{ return d[{offset} + i * {dims[1]} + j]; }}"
            )
        else:
            accessors.append(
                f"__host__ __device__ inline int {name}(const signed char *d, int i, int j, int k) "
                f"{{ return d[{offset} + (i * {dims[1]} + j) * {dims[2]} + k]; }}"
            )

    lines.append(f"constexpr int table_size = {len(blob)};")
    lines.append("constexpr signed char tables[table_size] = {")
    for i in range(0, len(blob), 20):
        lines.append("    " + ", ".join(str(x) for x in blob[i : i + 20]) + ",")
    lines.append("};")
    lines.append("")
    lines.extend(accessors)
    lines.append("")
    lines.append("}   // namespace mc33")
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"{len(tables)} tables, {len(blob)} bytes -> {out_path}")


if __name__ == "__main__":
    main()
