name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # platform: [windows-latest, ubuntu-latest]
        platform: [ubuntu-latest]
        python-version: ["3.8", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        method: 'network'
        sub-packages: '["nvcc", "cudart"]'

    - name: Build and install
      run: python -m pip install pytest
           pip install --verbose .

    - name: Install pytorch.
      run: python -m pip install torch --index-url https://download.pytorch.org/whl/cu121

    - name: Test
      run: python -m pytest
